/* The following code was generated by JFlex 1.4.1 on 25/04/2020 13:06 */

/*
 * 04/23/2019
 *
 * Maxence Miguel-Brebion 
 *
 * Latex Parser : improve code and format
 * 
 * 
 */
package TextEditor.Tex;
import java.io.IOException;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 25/04/2020 13:06 from the specification file
 * <tt>/Users/mbrebion/NetBeansProjects/ExerciceExplorer/src/TextEditor/Tex/LatexParser.flex</tt>
 */
public class LatexParserImpl extends LatexParserBase {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int TCOLSA = 5;
  public static final int YYINITIAL = 0;
  public static final int MLE = 4;
  public static final int ADDQ = 2;
  public static final int BLOCK = 1;
  public static final int TCOLSB = 6;
  public static final int ADDA = 3;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\17\1\0\1\5\23\0\1\5\1\6\1\0\1\6"+
    "\1\32\1\31\1\6\1\4\5\6\1\1\1\3\1\6\12\2\6\6"+
    "\5\1\1\34\12\1\1\40\1\22\11\1\1\6\1\11\1\6\1\6"+
    "\1\1\1\0\1\21\1\12\1\25\1\20\1\13\1\1\1\14\1\1"+
    "\1\15\2\1\1\27\1\1\1\16\1\26\1\36\1\23\1\33\1\30"+
    "\1\24\1\37\2\1\1\35\2\1\1\7\1\0\1\10\102\0\1\1"+
    "\10\0\1\1\26\0\1\1\1\0\1\1\4\0\5\1\2\0\2\1"+
    "\4\0\1\1\1\0\1\1\2\0\1\1\1\0\2\1\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\2\2\1\3\1\2\1\4\2\1\1\5"+
    "\1\6\1\2\1\6\1\7\1\10\1\1\1\11\7\2"+
    "\1\12\1\0\1\2\1\0\1\13\1\0\1\14\12\2"+
    "\1\15\6\2\1\0\1\15\6\2\1\0\1\16\3\2"+
    "\1\0\1\17\1\16\1\2\1\0\1\2\1\0\1\17"+
    "\1\2\2\0\1\20\1\2\2\0\1\21\1\0\1\20"+
    "\1\2\1\0\1\21\1\2\1\0\1\2\2\0\1\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\306\0\347"+
    "\0\u0108\0\347\0\347\0\u0129\0\347\0\u014a\0\u016b\0\347"+
    "\0\347\0\u018c\0\u01ad\0\u01ce\0\u01ef\0\u0210\0\u0231\0\u0252"+
    "\0\u0273\0\u0294\0\u02b5\0\u02d6\0\u02f7\0\u0318\0\u014a\0\u0339"+
    "\0\u035a\0\u01ad\0\u037b\0\u0210\0\u039c\0\u03bd\0\u03de\0\u03ff"+
    "\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4\0\u04c5\0\u04e6\0\u0507"+
    "\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac\0\u05cd\0\u05ee\0\347"+
    "\0\u060f\0\u0630\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5\0\u06f6"+
    "\0\u0717\0\u0738\0\u0759\0\u077a\0\u079b\0\347\0\u07bc\0\u07dd"+
    "\0\u07fe\0\u081f\0\347\0\u0840\0\u0861\0\u0882\0\u08a3\0\u08c4"+
    "\0\u08e5\0\u0906\0\347\0\u0927\0\347\0\u0948\0\u0969\0\u0882"+
    "\0\u098a\0\u09ab\0\u09cc\0\u09ed\0\u0a0e\0\347";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\3\11\1\12\1\13\1\11\2\12\1\14\5\11"+
    "\1\15\11\11\1\16\1\17\6\11\1\10\3\11\1\12"+
    "\1\13\1\11\1\20\1\21\1\22\5\11\1\15\11\11"+
    "\1\16\1\17\6\11\1\10\3\11\1\12\1\13\1\11"+
    "\1\20\1\23\1\22\5\11\1\15\11\11\1\16\1\17"+
    "\6\11\1\10\3\11\1\12\1\13\1\11\1\20\1\24"+
    "\1\22\5\11\1\15\11\11\1\16\1\17\6\11\1\10"+
    "\3\11\1\12\1\13\1\11\1\20\1\25\1\22\5\11"+
    "\1\15\11\11\1\16\1\17\6\11\1\10\3\11\1\12"+
    "\1\13\1\11\1\20\1\26\1\22\5\11\1\15\11\11"+
    "\1\16\1\17\6\11\1\10\3\11\1\12\1\13\1\11"+
    "\1\20\1\27\1\22\5\11\1\15\11\11\1\16\1\17"+
    "\6\11\42\0\3\11\2\0\1\11\2\0\1\30\5\11"+
    "\1\0\11\11\2\0\6\11\1\0\3\11\2\0\3\11"+
    "\1\30\1\31\1\32\3\11\1\0\1\11\1\33\2\11"+
    "\1\34\3\11\1\35\2\0\3\11\1\36\2\11\1\0"+
    "\16\37\1\0\11\37\2\0\6\37\1\0\16\40\1\0"+
    "\11\40\2\0\6\40\1\0\3\11\2\0\3\11\1\30"+
    "\1\31\1\32\3\11\1\0\4\11\1\41\4\11\2\0"+
    "\6\11\5\0\1\42\1\0\1\43\7\0\1\42\26\0"+
    "\1\24\11\0\1\24\26\0\1\25\11\0\1\25\26\0"+
    "\1\44\1\0\1\45\7\0\1\44\26\0\1\27\11\0"+
    "\1\27\22\0\3\11\2\0\3\11\1\30\5\11\1\0"+
    "\11\11\2\0\6\11\1\0\3\11\2\0\1\11\2\0"+
    "\1\30\1\11\1\46\3\11\1\0\11\11\2\0\6\11"+
    "\1\0\3\11\2\0\1\11\2\0\1\30\4\11\1\47"+
    "\1\0\3\11\1\50\5\11\2\0\6\11\1\0\3\11"+
    "\2\0\1\11\2\0\1\30\5\11\1\0\1\51\10\11"+
    "\2\0\6\11\1\0\3\11\2\0\1\11\2\0\1\30"+
    "\3\11\1\52\1\11\1\0\5\11\1\53\3\11\2\0"+
    "\6\11\1\0\3\11\2\0\1\11\2\0\1\30\5\11"+
    "\1\0\6\11\1\54\2\11\2\0\6\11\1\0\3\11"+
    "\2\0\1\11\2\0\1\30\5\11\1\0\1\11\1\55"+
    "\7\11\2\0\6\11\1\0\16\40\1\0\11\40\1\0"+
    "\1\12\6\40\1\0\3\11\2\0\1\11\2\0\1\30"+
    "\5\11\1\0\5\11\1\53\3\11\2\0\6\11\5\0"+
    "\1\43\11\0\1\43\26\0\1\45\11\0\1\45\22\0"+
    "\3\11\2\0\1\11\2\0\1\30\2\11\1\56\2\11"+
    "\1\0\11\11\2\0\6\11\1\0\3\11\2\0\1\11"+
    "\2\0\1\30\5\11\1\0\1\57\10\11\2\0\6\11"+
    "\1\0\3\11\2\0\1\11\1\60\1\0\1\30\5\11"+
    "\1\0\11\11\2\0\6\11\1\0\3\11\2\0\1\11"+
    "\2\0\1\30\5\11\1\0\1\61\10\11\2\0\6\11"+
    "\1\0\3\11\2\0\1\11\2\0\1\30\5\11\1\0"+
    "\4\11\1\62\4\11\2\0\6\11\1\0\3\11\2\0"+
    "\1\11\2\0\1\30\5\11\1\0\6\11\1\63\2\11"+
    "\2\0\6\11\1\0\3\11\2\0\1\11\2\0\1\30"+
    "\5\11\1\0\11\11\2\0\4\11\1\64\1\11\1\0"+
    "\3\11\2\0\1\11\2\0\1\30\5\11\1\0\11\11"+
    "\2\0\1\65\5\11\1\0\3\11\2\0\1\11\2\0"+
    "\1\30\3\11\1\66\1\11\1\0\11\11\2\0\6\11"+
    "\1\0\3\11\2\0\1\11\1\67\1\0\1\30\5\11"+
    "\1\0\11\11\2\0\6\11\17\0\1\70\22\0\3\11"+
    "\2\0\1\11\2\0\1\30\5\11\1\0\2\11\1\71"+
    "\6\11\2\0\6\11\1\0\3\11\2\0\1\11\2\0"+
    "\1\30\5\11\1\0\11\11\2\0\1\72\5\11\1\0"+
    "\3\11\2\0\1\11\2\0\1\30\5\11\1\0\7\11"+
    "\1\73\1\11\2\0\6\11\1\0\3\11\2\0\1\11"+
    "\2\0\1\30\5\11\1\0\10\11\1\74\2\0\6\11"+
    "\1\0\3\11\2\0\1\11\2\0\1\30\5\11\1\0"+
    "\4\11\1\75\4\11\2\0\6\11\1\0\3\11\2\0"+
    "\1\11\2\0\1\30\4\11\1\76\1\0\11\11\2\0"+
    "\6\11\1\0\2\77\7\0\5\77\1\0\11\77\2\0"+
    "\6\77\1\0\3\11\2\0\1\11\1\100\1\0\1\30"+
    "\5\11\1\0\11\11\2\0\6\11\1\0\3\11\2\0"+
    "\1\11\2\0\1\30\1\11\1\101\3\11\1\0\11\11"+
    "\2\0\6\11\1\0\3\11\2\0\1\11\2\0\1\30"+
    "\5\11\1\0\10\11\1\102\2\0\6\11\1\0\3\11"+
    "\2\0\1\11\2\0\1\30\5\11\1\0\11\11\2\0"+
    "\5\11\1\36\1\0\3\11\2\0\1\11\2\0\1\30"+
    "\3\11\1\103\1\11\1\0\11\11\2\0\6\11\1\0"+
    "\3\11\2\0\1\11\1\104\1\0\1\30\5\11\1\0"+
    "\11\11\2\0\6\11\1\0\2\77\5\0\1\105\1\0"+
    "\5\77\1\0\11\77\2\0\6\77\17\0\1\106\22\0"+
    "\3\11\2\0\1\11\2\0\1\30\5\11\1\0\11\11"+
    "\2\0\1\11\1\107\4\11\1\0\3\11\2\0\1\11"+
    "\1\110\1\0\1\30\5\11\1\0\11\11\2\0\6\11"+
    "\1\0\3\11\2\0\1\11\2\0\1\30\1\11\1\111"+
    "\3\11\1\0\11\11\2\0\6\11\1\0\2\112\7\0"+
    "\5\112\1\0\11\112\2\0\6\112\17\0\1\113\22\0"+
    "\3\11\2\0\1\11\2\0\1\30\5\11\1\0\11\11"+
    "\2\0\2\11\1\114\3\11\2\0\1\115\37\0\3\11"+
    "\2\0\1\11\1\116\1\0\1\30\5\11\1\0\11\11"+
    "\2\0\6\11\1\0\2\112\5\0\1\117\1\0\5\112"+
    "\1\0\11\112\2\0\6\112\1\0\3\11\2\0\1\11"+
    "\2\0\1\30\1\11\1\120\3\11\1\0\11\11\2\0"+
    "\6\11\2\0\1\115\1\121\4\0\1\122\31\0\6\116"+
    "\1\0\1\123\1\124\5\116\1\0\11\116\2\0\6\116"+
    "\17\0\1\125\22\0\3\11\2\0\1\11\2\0\1\30"+
    "\5\11\1\0\11\11\2\0\1\126\5\11\2\0\1\121"+
    "\5\0\1\122\37\0\1\127\32\0\7\116\1\130\1\124"+
    "\5\116\1\0\11\116\2\0\6\116\1\0\3\11\2\0"+
    "\1\11\2\0\1\30\5\11\1\0\5\11\1\131\3\11"+
    "\2\0\6\11\2\0\1\132\37\0\3\11\2\0\1\11"+
    "\2\0\1\30\3\11\1\133\1\11\1\0\11\11\2\0"+
    "\6\11\2\0\1\132\1\134\4\0\1\135\31\0\3\11"+
    "\2\0\1\11\2\0\1\30\5\11\1\0\5\11\1\103"+
    "\3\11\2\0\6\11\2\0\1\134\5\0\1\135\37\0"+
    "\1\136\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2607];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\1\1\2\11\1\1\1\11\2\1\2\11"+
    "\16\1\1\0\1\1\1\0\1\1\1\0\22\1\1\0"+
    "\1\11\6\1\1\0\4\1\1\0\1\1\1\11\1\1"+
    "\1\0\1\1\1\0\1\11\1\1\2\0\2\1\2\0"+
    "\1\11\1\0\1\11\1\1\1\0\2\1\1\0\1\1"+
    "\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */

	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public LatexParserImpl() {
            super();
	}

        
 @Override
    public void startParsing() {
        yybegin(YYINITIAL);
        try {
            yylex();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
            



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LatexParserImpl(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LatexParserImpl(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public boolean yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { this.endLine();
          }
        case 19: break;
        case 6: 
          { addCloseBracket();
          }
        case 20: break;
        case 14: 
          { this.startADDQ();
          }
        case 21: break;
        case 16: 
          { // find block name in \begin{name}
                                             String name = yytext().substring(7, yytext().length()-2);
                                             // start new block
                                                this.startBlock(name);
          }
        case 22: break;
        case 15: 
          { // end previous block
                                             this.endBlock();
          }
        case 23: break;
        case 18: 
          { this.startTcolsA();
          }
        case 24: break;
        case 2: 
          { this.currentLine+=yytext();
          }
        case 25: break;
        case 10: 
          { this.currentLine += yytext();
          }
        case 26: break;
        case 12: 
          { bracketCount--; endTcolsA() ; bracketCount++;
          }
        case 27: break;
        case 11: 
          { bracketCount--; endADDQ() ; bracketCount++;
          }
        case 28: break;
        case 1: 
          { System.err.println("not catched : " + yytext());
          }
        case 29: break;
        case 5: 
          { addOpenBracket();
          }
        case 30: break;
        case 7: 
          { endADDA();
          }
        case 31: break;
        case 8: 
          { endEq();
          }
        case 32: break;
        case 3: 
          { this.addWhiteSpace();
          }
        case 33: break;
        case 13: 
          { startEq();
          }
        case 34: break;
        case 9: 
          { endTcolsB();
          }
        case 35: break;
        case 17: 
          { 
          }
        case 36: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case TCOLSA: {
              return false;
            }
            case 95: break;
            case YYINITIAL: {
              return false;
            }
            case 96: break;
            case MLE: {
              return false;
            }
            case 97: break;
            case ADDQ: {
              return false;
            }
            case 98: break;
            case BLOCK: {
              return false;
            }
            case 99: break;
            case TCOLSB: {
              return false;
            }
            case 100: break;
            case ADDA: {
              return false;
            }
            case 101: break;
            default:
            return false;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
