/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Helper.Utils;
import TexRessources.TexWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;

/**
 *
 * @author mbrebion
 */
public class CompoEditor extends javax.swing.JPanel {

    StyledDocument doc;

    /**
     * Creates new form SubjectEditor
     */
    public CompoEditor() {
        initComponents();
    }

    public CompoEditor(List<String> lines) {
        initComponents();
        this.doc = jTextPane1.getStyledDocument();
        this.setText(lines);
    }

    protected void setText(List<String> lines) {
        jTextPane1.setText("");
        for (String line : lines) {
            this.append(line);
        }
    }

    protected void append(String s) {
        try {
            if (doc.getLength() == 0) {
                doc.insertString(0, s, null);
            } else {
                doc.insertString(doc.getLength(), "\n" + s, null);
            }

        } catch (BadLocationException ex) {
            Logger.getLogger(TextEditorBinded.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    protected List<String> getLines() {
        String[] split = jTextPane1.getText().split("\n");
        List<String> lines = new ArrayList<>();
        for (String s : split) {
            lines.add(s);
        }
        return lines;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        compileButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        compileButton.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        compileButton.setText("Compiler");
        compileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 250, Short.MAX_VALUE)
                .addComponent(compileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(compileButton)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void compileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileButtonActionPerformed
        List<String> lines = this.getLines();

        TexWriter.writeTexFile(lines);
        if (TexWriter.latexToPdf()) {
            TexWriter.openPdf();
        } else {
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            Utils.showLongTextMessageInDialog(TexWriter.latexLog, topFrame);
        }


    }//GEN-LAST:event_compileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compileButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
