/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import exerciceexplorer.Exercice;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author mbrebion
 */
public class ReadmeEditor extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form SubjectEditor
     */
    protected Exercice ex;
    
    public ReadmeEditor() {
        initComponents();
    }

    public ReadmeEditor(Exercice ex) {
        initComponents();
        this.ex=ex;
        this.textEditorBinded1.bindToFile(ex.getReadmePath());
        this.textEditorBinded1.addObserver(this);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textEditorBinded1 = new View.TextEditorBinded();

        setLayout(new java.awt.BorderLayout());
        add(textEditorBinded1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.TextEditorBinded textEditorBinded1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        ex.NotifyReadmeChanged();
    }
    
    public void saveFile(){
        this.textEditorBinded1.SaveFile();
    }
}
