/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import exerciceexplorer.Exercice;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JMenuBar;

/**
 *
 * @author mbrebion
 */
public class SubjectEditor extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form SubjectEditor
     */
    protected Exercice ex;
    
    public SubjectEditor() {
        initComponents();
    }
    
    public SubjectEditor(Exercice ex) {
        initComponents();
        this.ex = ex;
        this.textEditorBinded1.bindToFile(ex.getSubjectPath());
        this.textEditorBinded1.addObserver(this);
        
    }
    
    public void updateColoring() {
        this.textEditorBinded1.updateColoring();
    }
    
    public void setMenuBar(JMenuBar jmb) {
        this.textEditorBinded1.setMenuBar(jmb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textEditorBinded1 = new View.TextEditorBinded();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textEditorBinded1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(textEditorBinded1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.TextEditorBinded textEditorBinded1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        ex.NotifySubjectChanged();
        
    }
    
    public void updateMenuBarView(boolean show) {
        this.textEditorBinded1.updateMenuBarView(show);
    }
    
    public void saveFile() {
        this.textEditorBinded1.saveFile();
    }
    
    
    public boolean needSaving(){
        return this.textEditorBinded1.hasChanged();
    }
}
