/* The following code was generated by JFlex 1.4.1 on 25/04/2020 13:06 */

/*
 * 04/23/2019
 *
 * Maxence Miguel-Brebion 
 *
 * Latex Parser : improve code and format
 * 
 * 
 */
package TextEditor.Tex.Indenting;
import java.io.IOException;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 25/04/2020 13:06 from the specification file
 * <tt>/Users/mbrebion/NetBeansProjects/ExerciceExplorer/src/TextEditor/Tex/Indenting/LatexIndenter.flex</tt>
 */
public class LatexIndenterImpl extends LatexIndenterBase {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int BLOCK_A = 2;
  public static final int YYINITIAL = 0;
  public static final int BLOCK_Q = 1;
  public static final int BRACKET_BLOCK = 3;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\21\1\0\1\5\23\0\1\5\3\6\1\34\1\33"+
    "\1\6\1\4\5\6\1\1\1\3\1\6\12\2\6\6\5\1\1\36"+
    "\12\1\1\42\1\24\11\1\1\17\1\11\1\20\1\6\1\1\1\0"+
    "\1\23\1\12\1\27\1\22\1\13\1\1\1\14\1\1\1\15\2\1"+
    "\1\31\1\1\1\16\1\30\1\40\1\25\1\35\1\32\1\26\1\41"+
    "\2\1\1\37\2\1\1\7\1\6\1\10\1\6\101\0\1\1\10\0"+
    "\1\1\26\0\1\1\1\0\1\1\4\0\5\1\2\0\2\1\4\0"+
    "\1\1\1\0\1\1\2\0\1\1\1\0\2\1\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\2\2\1\3\1\2\1\4\2\1\1\5"+
    "\1\6\1\3\1\7\1\2\1\4\7\2\1\10\2\0"+
    "\1\7\14\2\1\11\6\2\1\0\7\2\1\0\5\2"+
    "\1\0\1\12\3\2\1\0\1\2\1\0\1\11\2\2"+
    "\3\0\1\11\1\2\2\0\1\13\3\0\1\14\1\2"+
    "\1\0\2\13\4\0\1\2\2\0\1\2\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\151\0\106\0\214\0\106\0\106"+
    "\0\257\0\106\0\322\0\365\0\106\0\106\0\u0118\0\u013b"+
    "\0\u015e\0\u0118\0\u0181\0\u01a4\0\u01c7\0\u01ea\0\u020d\0\u0230"+
    "\0\u0253\0\322\0\u0276\0\u0118\0\u0299\0\u02bc\0\u02df\0\u0302"+
    "\0\u0325\0\u0348\0\u036b\0\u038e\0\u03b1\0\u03d4\0\u03f7\0\u041a"+
    "\0\u043d\0\u0460\0\u0483\0\u04a6\0\u04c9\0\u04ec\0\u050f\0\u0532"+
    "\0\u0555\0\u0578\0\u059b\0\u05be\0\u05e1\0\u0604\0\u0627\0\u064a"+
    "\0\u066d\0\u0690\0\u06b3\0\u06d6\0\u06f9\0\u071c\0\u073f\0\u0762"+
    "\0\u0785\0\u07a8\0\u07cb\0\u07ee\0\u0811\0\u0834\0\u0857\0\u087a"+
    "\0\u089d\0\u08c0\0\u08e3\0\u0906\0\106\0\u0929\0\u094c\0\u096f"+
    "\0\u0992\0\u09b5\0\u09d8\0\u09fb\0\u0a1e\0\u0a41\0\u0a64\0\106"+
    "\0\u0a87\0\u0aaa\0\u0acd\0\u0af0\0\u0b13\0\u0b36\0\u0b59\0\u0b7c"+
    "\0\u0b9f\0\u0bc2\0\u0be5";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\3\6\1\7\1\10\1\6\2\7\1\11\7\6"+
    "\1\12\11\6\1\13\1\14\6\6\7\5\1\15\1\16"+
    "\10\5\1\0\21\5\43\0\1\5\3\6\1\7\1\17"+
    "\1\6\1\15\1\20\1\21\7\6\1\22\11\6\1\13"+
    "\1\14\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\7\6\1\0\11\6\2\0\6\6\1\0\3\6\2\0"+
    "\3\6\1\23\1\24\1\25\5\6\1\0\1\6\1\26"+
    "\2\6\1\27\3\6\1\30\2\0\3\6\1\31\2\6"+
    "\1\0\20\32\1\0\11\32\2\0\6\32\1\0\20\33"+
    "\1\0\11\33\2\0\6\33\5\0\1\34\2\0\1\20"+
    "\10\0\1\34\26\0\1\20\1\0\1\35\11\0\1\20"+
    "\22\0\3\6\2\0\3\6\1\23\1\24\1\25\5\6"+
    "\1\0\1\6\1\26\2\6\1\36\4\6\2\0\6\6"+
    "\1\0\3\6\2\0\3\6\1\23\7\6\1\0\11\6"+
    "\2\0\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\1\6\1\37\5\6\1\0\11\6\2\0\6\6\1\0"+
    "\3\6\2\0\1\6\2\0\1\23\4\6\1\40\2\6"+
    "\1\0\3\6\1\41\5\6\2\0\6\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\23\7\6\1\0\1\42\10\6"+
    "\2\0\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\3\6\1\43\3\6\1\0\5\6\1\44\3\6\2\0"+
    "\6\6\1\0\3\6\2\0\1\6\2\0\1\23\7\6"+
    "\1\0\6\6\1\45\2\6\2\0\6\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\23\7\6\1\0\1\6\1\46"+
    "\7\6\2\0\6\6\1\0\20\33\1\0\11\33\1\0"+
    "\1\7\6\33\5\0\1\35\13\0\1\35\22\0\3\6"+
    "\2\0\1\6\2\0\1\23\7\6\1\0\5\6\1\44"+
    "\3\6\2\0\6\6\1\0\3\6\2\0\1\6\2\0"+
    "\1\23\2\6\1\47\4\6\1\0\11\6\2\0\6\6"+
    "\1\0\3\6\2\0\1\6\2\0\1\23\7\6\1\0"+
    "\1\50\5\6\1\51\2\6\2\0\6\6\1\0\3\6"+
    "\2\0\1\6\1\52\1\0\1\23\7\6\1\0\11\6"+
    "\2\0\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\7\6\1\0\1\53\10\6\2\0\6\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\23\7\6\1\0\4\6\1\54"+
    "\4\6\2\0\6\6\1\0\3\6\2\0\1\6\2\0"+
    "\1\23\7\6\1\0\6\6\1\55\2\6\2\0\6\6"+
    "\1\0\3\6\2\0\1\6\2\0\1\23\7\6\1\0"+
    "\11\6\2\0\4\6\1\56\1\6\1\0\3\6\2\0"+
    "\1\6\2\0\1\23\7\6\1\0\11\6\2\0\1\57"+
    "\5\6\1\0\3\6\2\0\1\6\2\0\1\23\3\6"+
    "\1\60\3\6\1\0\11\6\2\0\6\6\1\0\3\6"+
    "\2\0\1\6\1\61\1\0\1\23\7\6\1\0\11\6"+
    "\2\0\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\4\6\1\62\2\6\1\0\11\6\2\0\6\6\5\0"+
    "\1\52\13\0\1\52\22\0\3\6\2\0\1\6\2\0"+
    "\1\23\7\6\1\0\2\6\1\63\6\6\2\0\6\6"+
    "\1\0\3\6\2\0\1\6\2\0\1\23\7\6\1\0"+
    "\11\6\2\0\1\64\5\6\1\0\3\6\2\0\1\6"+
    "\2\0\1\23\7\6\1\0\7\6\1\65\1\6\2\0"+
    "\6\6\1\0\3\6\2\0\1\6\2\0\1\23\7\6"+
    "\1\0\10\6\1\66\2\0\6\6\1\0\3\6\2\0"+
    "\1\6\2\0\1\23\7\6\1\0\4\6\1\67\4\6"+
    "\2\0\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\4\6\1\70\2\6\1\0\11\6\2\0\6\6\1\0"+
    "\2\71\7\0\5\71\3\0\11\71\2\0\6\71\1\0"+
    "\3\6\2\0\1\6\2\0\1\23\7\6\1\0\5\6"+
    "\1\72\3\6\2\0\6\6\1\0\3\6\2\0\1\6"+
    "\1\52\1\0\1\23\5\6\1\73\1\6\1\0\11\6"+
    "\2\0\6\6\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\1\6\1\74\5\6\1\0\11\6\2\0\6\6\1\0"+
    "\3\6\2\0\1\6\2\0\1\23\7\6\1\0\10\6"+
    "\1\75\2\0\6\6\1\0\3\6\2\0\1\6\2\0"+
    "\1\23\7\6\1\0\11\6\2\0\5\6\1\31\1\0"+
    "\3\6\2\0\1\6\2\0\1\23\3\6\1\76\3\6"+
    "\1\0\11\6\2\0\6\6\1\0\3\6\2\0\1\6"+
    "\1\77\1\0\1\23\7\6\1\0\11\6\2\0\6\6"+
    "\1\0\2\71\5\0\1\100\1\0\5\71\3\0\11\71"+
    "\2\0\6\71\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\1\6\1\101\5\6\1\0\11\6\2\0\6\6\1\0"+
    "\2\102\1\6\2\0\1\6\2\0\1\23\5\102\2\6"+
    "\1\0\11\102\2\0\6\102\1\0\3\6\2\0\1\6"+
    "\2\0\1\23\7\6\1\0\11\6\2\0\1\6\1\103"+
    "\4\6\1\0\3\6\2\0\1\6\1\104\1\0\1\23"+
    "\7\6\1\0\11\6\2\0\6\6\1\0\3\6\2\0"+
    "\1\6\2\0\1\23\1\6\1\105\5\6\1\0\11\6"+
    "\2\0\6\6\1\0\2\106\7\0\5\106\3\0\11\106"+
    "\2\0\6\106\21\0\1\100\22\0\3\6\2\0\1\6"+
    "\1\107\1\0\1\23\7\6\1\0\11\6\2\0\6\6"+
    "\1\0\2\102\1\6\2\0\1\6\2\0\1\23\5\102"+
    "\1\6\1\110\1\0\11\102\2\0\6\102\1\0\3\6"+
    "\2\0\1\6\2\0\1\23\7\6\1\0\11\6\2\0"+
    "\2\6\1\111\3\6\2\0\1\112\41\0\3\6\2\0"+
    "\1\6\1\113\1\0\1\23\7\6\1\0\11\6\2\0"+
    "\6\6\1\0\2\106\5\0\1\114\1\0\5\106\3\0"+
    "\11\106\2\0\6\106\21\0\1\107\22\0\3\6\2\0"+
    "\1\6\1\115\1\0\1\23\7\6\1\0\11\6\2\0"+
    "\6\6\1\0\3\6\2\0\1\6\2\0\1\23\1\6"+
    "\1\116\5\6\1\0\11\6\2\0\6\6\2\0\1\112"+
    "\1\117\4\0\1\120\33\0\6\113\1\0\1\121\1\122"+
    "\7\113\1\0\11\113\2\0\6\113\7\0\1\123\7\0"+
    "\1\124\1\0\1\125\22\0\3\6\2\0\1\6\2\0"+
    "\1\23\7\6\1\0\11\6\2\0\1\126\5\6\2\0"+
    "\1\117\5\0\1\120\41\0\1\127\54\0\1\130\22\0"+
    "\7\113\1\131\1\122\7\113\1\0\11\113\2\0\6\113"+
    "\1\0\3\123\2\0\1\123\1\0\1\132\1\133\7\123"+
    "\1\0\11\123\2\0\6\123\1\0\3\124\2\0\1\124"+
    "\2\0\1\134\6\124\1\135\1\0\11\124\2\0\6\124"+
    "\21\0\1\125\22\0\3\6\2\0\1\6\2\0\1\23"+
    "\7\6\1\0\5\6\1\136\3\6\2\0\6\6\2\0"+
    "\1\137\41\0\6\113\1\0\1\121\1\122\7\113\1\130"+
    "\11\113\2\0\6\113\7\0\1\123\11\0\1\125\22\0"+
    "\3\123\2\0\2\123\1\140\1\133\7\123\1\0\11\123"+
    "\2\0\6\123\1\0\3\124\2\0\3\124\1\134\6\124"+
    "\1\135\1\0\11\124\2\0\6\124\1\0\3\124\2\0"+
    "\1\124\1\123\1\0\1\134\6\124\1\135\1\125\11\124"+
    "\2\0\6\124\1\0\3\6\2\0\1\6\2\0\1\23"+
    "\3\6\1\141\3\6\1\0\11\6\2\0\6\6\2\0"+
    "\1\137\1\142\4\0\1\143\33\0\3\123\2\0\2\123"+
    "\1\132\1\133\7\123\1\125\11\123\2\0\6\123\1\0"+
    "\3\6\2\0\1\6\2\0\1\23\7\6\1\0\5\6"+
    "\1\76\3\6\2\0\6\6\2\0\1\142\5\0\1\143"+
    "\41\0\1\107\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3080];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\10\1\0\1\11\1\1\2\11\1\1\1\11"+
    "\2\1\2\11\14\1\2\0\24\1\1\0\7\1\1\0"+
    "\5\1\1\0\4\1\1\0\1\1\1\0\3\1\3\0"+
    "\1\11\1\1\2\0\1\1\3\0\2\1\1\0\1\11"+
    "\1\1\4\0\1\1\2\0\1\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */

	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public LatexIndenterImpl() {
            super();
	}

        
 @Override
    public void startParsing() {
        yybegin(YYINITIAL);
        try {
            yylex();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
            



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LatexIndenterImpl(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LatexIndenterImpl(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public boolean yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { startBracketBloc(yytext());
          }
        case 13: break;
        case 12: 
          { this.startBlock();
          }
        case 14: break;
        case 4: 
          { this.endLine();
          }
        case 15: break;
        case 6: 
          { addCloseBracket();
          }
        case 16: break;
        case 10: 
          { this.endBlock();
          }
        case 17: break;
        case 3: 
          { this.addWhiteSpace();
          }
        case 18: break;
        case 8: 
          { this.currentLine += yytext();
          }
        case 19: break;
        case 5: 
          { addOpenBracket();
          }
        case 20: break;
        case 11: 
          { this.currentLine+=yytext().trim(); this.endLine();
          }
        case 21: break;
        case 2: 
          { this.currentLine+=yytext();
          }
        case 22: break;
        case 7: 
          { endBracketBlock() ;
          }
        case 23: break;
        case 1: 
          { System.err.println("not catched : " + yytext());
          }
        case 24: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              this.endLine(); return false;
            }
            case 100: break;
            case BLOCK_Q: {
              return false;
            }
            case 101: break;
            case BRACKET_BLOCK: {
              return false;
            }
            case 102: break;
            default:
            return false;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
