/* The following code was generated by JFlex 1.4.1 on 25/04/2020 13:06 */

/*
 * 04/24/2012
 *
 * Maxence Miguel-Brebion 
 *
 * LatexTokenMaker.java - Scanner for LaTeX.
 * 
 * This library is distributed under a modified BSD license.  See the included
 * LICENSE file for details.
 */
package TextEditor.Tex.Coloring;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * If you wish to regenerate this file yourself, keep in mind the following:
 * <ul>
 *   <li>The generated <code>LatexTokenMaker.java</code> file will contain two
 *       definitions of both <code>zzRefill</code> and <code>yyreset</code>.
 *       You should hand-delete the second of each definition (the ones
 *       generated by the lexer), as these generated methods modify the input
 *       buffer, which we'll never have to do.</li>
 *   <li>You should also change the declaration/definition of zzBuffer to NOT
 *       be initialized.  This is a needless memory allocation for us since we
 *       will be pointing the array somewhere else anyway.</li>
 *   <li>You should NOT call <code>yylex()</code> on the generated scanner
 *       directly; rather, you should use <code>getTokenList</code> as you would
 *       with any other <code>TokenMaker</code> instance.</li>
 * </ul>
 *
 * @author Robert Futrell & Maxence Miguel-Brebion
 * @version 0.6
 *
 */

public class LatexTokenMaker extends AbstractJFlexTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int HIDDEN_ADDQ = 5;
  public static final int EOL_COMMENT = 1;
  public static final int MLE_IN_A = 4;
  public static final int MLE = 2;
  public static final int ADDA = 8;
  public static final int MLE_IN_Q = 3;
  public static final int ADDQ = 7;
  public static final int YYINITIAL = 0;
  public static final int HIDDEN_ADDA = 6;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\37\1\0\1\3\23\0\1\3\3\5\1\20\1\4"+
    "\1\5\1\2\5\5\1\1\2\5\12\1\6\5\5\1\1\27\12\1"+
    "\1\36\1\15\11\1\1\16\1\10\1\17\1\5\1\1\1\0\1\13"+
    "\1\21\1\31\1\14\1\11\1\1\1\22\1\1\1\23\4\1\1\24"+
    "\1\34\1\32\1\12\1\26\1\33\1\25\1\35\2\1\1\30\2\1"+
    "\1\6\1\5\1\7\1\5\101\0\1\1\10\0\1\1\26\0\1\1"+
    "\1\0\1\1\4\0\5\1\2\0\2\1\4\0\1\1\1\0\1\1"+
    "\2\0\1\1\1\0\2\1\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\11\0\2\1\1\2\1\3\1\4\2\1\1\5\1\3"+
    "\2\6\1\7\1\10\1\6\2\11\1\12\1\11\2\13"+
    "\1\14\1\13\2\15\1\16\1\17\1\15\2\20\1\21"+
    "\1\22\1\20\1\23\1\1\1\23\1\24\1\25\1\1"+
    "\1\24\1\1\1\26\1\27\6\26\1\0\11\26\1\30"+
    "\2\26\1\31\6\26\1\32\1\33\1\0\5\26\1\0"+
    "\1\34\1\1\4\26\1\35\1\1\1\0\3\26\1\1"+
    "\1\0\1\26\1\0\1\26\1\36\1\37\1\26\1\40"+
    "\1\0\2\26\1\40\4\26\1\0\1\26\1\41\1\0"+
    "\1\26\1\41\1\0\1\42\1\0\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\140\0\200\0\240\0\300\0\340"+
    "\0\u0100\0\u0120\0\u0140\0\u0120\0\u0160\0\u0120\0\u0180\0\u01a0"+
    "\0\u0120\0\u0120\0\u0120\0\u01c0\0\u0120\0\u0120\0\u01e0\0\u0120"+
    "\0\u0200\0\u0120\0\u0220\0\u0120\0\u0240\0\u0120\0\u0260\0\u0120"+
    "\0\u0280\0\u0120\0\u0120\0\u02a0\0\u0120\0\u02c0\0\u0120\0\u0120"+
    "\0\u02e0\0\u0120\0\u0300\0\u01a0\0\u0120\0\u0120\0\u0320\0\u01a0"+
    "\0\u0340\0\u0360\0\u0120\0\u0380\0\u03a0\0\u03c0\0\u03e0\0\u0400"+
    "\0\u0420\0\u0440\0\u0460\0\u0480\0\u04a0\0\u04c0\0\u04e0\0\u0500"+
    "\0\u0520\0\u0540\0\u0560\0\u0120\0\u0580\0\u05a0\0\u0120\0\u05c0"+
    "\0\u05e0\0\u0600\0\u0620\0\u0640\0\u0660\0\u0120\0\u0120\0\u0680"+
    "\0\u06a0\0\u06c0\0\u06e0\0\u0700\0\u0720\0\u0740\0\u0120\0\u0760"+
    "\0\u0780\0\u07a0\0\u07c0\0\u07e0\0\u0120\0\u0800\0\u0820\0\u0840"+
    "\0\u0860\0\u0880\0\u08a0\0\u08c0\0\u08e0\0\u0900\0\u0920\0\u0120"+
    "\0\u0120\0\u0940\0\u0120\0\u0960\0\u0980\0\u09a0\0\u0900\0\u09c0"+
    "\0\u09e0\0\u0a00\0\u0a20\0\u0a40\0\u0a60\0\u0120\0\u0a80\0\u0aa0"+
    "\0\u0a40\0\u0ac0\0\u0120\0\u0ae0\0\u0ac0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\12\1\13\1\12\1\14\1\15\1\13\2\16\1\17"+
    "\7\13\1\20\16\13\1\21\37\22\1\0\1\23\1\24"+
    "\2\23\1\15\1\24\1\25\1\26\1\27\7\24\1\23"+
    "\16\24\1\0\1\30\1\31\2\30\1\15\1\31\1\25"+
    "\1\32\1\33\7\31\1\30\16\31\1\0\1\34\1\35"+
    "\2\34\1\15\1\35\1\25\1\36\1\37\7\35\1\34"+
    "\16\35\1\0\1\40\1\41\3\40\1\41\1\42\1\43"+
    "\1\44\7\41\1\40\16\41\1\0\1\45\1\46\3\45"+
    "\1\46\1\47\1\50\1\51\7\46\1\45\16\46\1\0"+
    "\1\52\1\13\1\12\1\14\1\15\1\13\1\25\1\36"+
    "\1\53\7\13\1\54\16\13\1\0\1\55\1\13\1\12"+
    "\1\14\1\15\1\13\1\56\1\26\1\57\7\13\1\60"+
    "\16\13\42\0\1\13\3\0\1\13\2\0\1\61\7\13"+
    "\1\0\16\13\2\0\3\15\1\0\32\15\2\0\1\62"+
    "\2\0\1\63\3\13\1\61\1\64\1\62\1\65\2\62"+
    "\2\13\1\0\1\66\3\62\1\67\4\62\1\70\1\71"+
    "\3\62\2\0\3\72\1\0\13\72\1\0\16\72\2\0"+
    "\1\24\3\0\1\24\2\0\1\27\7\24\1\0\16\24"+
    "\2\0\1\24\3\0\3\24\1\27\7\24\1\0\16\24"+
    "\2\0\1\31\3\0\1\31\2\0\1\33\7\31\1\0"+
    "\16\31\2\0\1\31\3\0\3\31\1\33\7\31\1\0"+
    "\16\31\2\0\1\35\3\0\1\35\2\0\1\37\7\35"+
    "\1\0\16\35\2\0\1\35\3\0\3\35\1\37\7\35"+
    "\1\0\16\35\2\0\1\41\3\0\1\41\2\0\1\44"+
    "\7\41\1\0\16\41\2\0\1\41\3\0\3\41\1\44"+
    "\7\41\1\0\16\41\2\0\1\46\3\0\1\46\2\0"+
    "\1\51\7\46\1\0\16\46\2\0\1\46\3\0\3\46"+
    "\1\51\7\46\1\0\16\46\2\0\1\62\2\0\1\63"+
    "\3\13\1\61\1\73\4\62\2\13\1\0\1\66\15\62"+
    "\2\0\1\62\2\0\1\63\3\13\1\61\1\74\4\62"+
    "\2\13\1\0\1\66\15\62\2\0\1\13\3\0\3\13"+
    "\1\61\7\13\1\0\16\13\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\5\62\2\13\1\0\16\62\2\0\1\62"+
    "\3\0\1\13\2\0\1\61\1\62\1\75\3\62\2\13"+
    "\1\0\3\62\1\76\12\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\3\62\1\77\1\62\2\13\1\0\16\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\1\100\4\62"+
    "\2\13\1\0\16\62\2\0\1\62\3\0\1\13\2\0"+
    "\1\61\5\62\2\13\1\0\2\62\1\101\13\62\2\0"+
    "\1\62\3\0\1\13\2\0\1\61\2\62\1\102\2\62"+
    "\2\13\1\0\16\62\2\0\1\62\3\0\1\13\2\0"+
    "\1\61\5\62\2\13\1\0\13\62\1\103\2\62\2\0"+
    "\3\72\1\0\13\72\1\104\16\72\2\0\1\62\3\0"+
    "\1\13\2\0\1\61\1\62\1\105\3\62\2\13\1\0"+
    "\3\62\1\76\12\62\2\0\1\62\3\0\1\13\2\0"+
    "\1\61\1\62\1\106\3\62\2\13\1\0\3\62\1\76"+
    "\12\62\2\0\1\62\3\0\1\13\1\107\1\0\1\61"+
    "\5\62\2\13\1\0\16\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\3\62\1\110\1\62\2\13\1\0\16\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\3\62\1\111"+
    "\1\62\2\13\1\0\16\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\5\62\2\13\1\0\1\62\1\112\14\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\5\62\2\13"+
    "\1\0\4\62\1\113\11\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\5\62\2\13\1\0\5\62\1\114\10\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\5\62\2\13"+
    "\1\0\14\62\1\115\1\62\2\0\1\62\3\0\1\13"+
    "\1\116\1\0\1\61\5\62\2\13\1\0\16\62\2\0"+
    "\1\62\3\0\1\13\1\117\1\0\1\61\5\62\2\13"+
    "\1\0\16\62\2\0\1\62\3\0\1\13\1\120\1\0"+
    "\1\61\5\62\2\13\1\0\16\62\2\0\1\62\3\0"+
    "\1\13\2\0\1\61\4\62\1\121\2\13\1\0\16\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\5\62\2\13"+
    "\1\0\2\62\1\122\13\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\5\62\2\13\1\0\5\62\1\123\10\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\5\62\2\13"+
    "\1\0\4\62\1\124\11\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\5\62\2\13\1\0\12\62\1\125\3\62"+
    "\2\0\1\126\7\0\5\126\3\0\16\126\2\0\1\62"+
    "\3\0\1\13\1\127\1\0\1\61\5\62\1\130\1\13"+
    "\1\0\16\62\2\0\1\62\3\0\1\13\2\0\1\61"+
    "\5\62\2\13\1\0\3\62\1\131\12\62\2\0\1\62"+
    "\3\0\1\13\2\0\1\61\1\132\4\62\2\13\1\0"+
    "\16\62\2\0\1\62\3\0\1\13\2\0\1\61\5\62"+
    "\2\13\1\0\2\62\1\133\13\62\2\0\1\62\3\0"+
    "\1\13\2\0\1\61\5\62\2\13\1\0\15\62\1\134"+
    "\2\0\1\126\5\0\1\135\1\0\5\126\3\0\16\126"+
    "\2\0\1\136\3\0\1\13\2\0\1\61\5\136\2\13"+
    "\1\0\16\136\2\0\1\62\3\0\1\13\1\137\1\0"+
    "\1\61\5\62\2\13\1\0\16\62\2\0\1\62\3\0"+
    "\1\13\2\0\1\61\5\62\2\13\1\0\6\62\1\140"+
    "\7\62\2\0\1\62\3\0\1\13\2\0\1\61\1\141"+
    "\4\62\2\13\1\0\16\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\2\62\1\142\2\62\2\13\1\0\16\62"+
    "\2\0\1\136\3\0\1\13\2\0\1\61\5\136\1\13"+
    "\1\143\1\0\16\136\2\0\1\144\7\0\5\144\3\0"+
    "\16\144\2\0\1\62\3\0\1\13\2\0\1\61\5\62"+
    "\2\13\1\0\7\62\1\145\6\62\2\0\1\62\3\0"+
    "\1\13\1\146\1\0\1\61\5\62\2\13\1\0\16\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\5\62\2\13"+
    "\1\0\5\62\1\147\10\62\2\0\1\13\3\0\1\13"+
    "\1\150\1\0\1\61\7\13\1\0\16\13\2\0\1\144"+
    "\5\0\1\151\1\0\5\144\3\0\16\144\2\0\1\62"+
    "\3\0\1\13\2\0\1\61\1\152\4\62\2\13\1\0"+
    "\16\62\2\0\3\146\1\0\1\146\1\0\1\153\1\154"+
    "\7\146\1\0\16\146\2\0\1\62\3\0\1\13\2\0"+
    "\1\61\5\62\2\13\1\0\4\62\1\155\11\62\2\0"+
    "\1\62\3\0\1\13\2\0\1\61\5\62\2\13\1\0"+
    "\5\62\1\156\10\62\2\0\3\146\1\0\2\146\1\157"+
    "\1\154\7\146\1\0\16\146\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\5\62\2\13\1\0\2\62\1\160\13\62"+
    "\2\0\1\62\3\0\1\13\2\0\1\61\5\62\2\13"+
    "\1\0\10\62\1\161\5\62\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\1\162\4\62\2\13\1\0\16\62\2\0"+
    "\1\62\3\0\1\13\2\0\1\61\5\62\2\13\1\0"+
    "\2\62\1\163\13\62\2\0\1\62\3\0\1\13\1\164"+
    "\1\0\1\61\5\62\2\13\1\0\16\62\2\0\1\62"+
    "\3\0\1\13\2\0\1\61\5\62\2\13\1\0\10\62"+
    "\1\165\5\62\2\0\3\164\1\0\1\164\1\0\1\166"+
    "\1\167\7\164\1\0\16\164\2\0\1\62\3\0\1\13"+
    "\2\0\1\61\1\170\4\62\2\13\1\0\16\62\2\0"+
    "\3\164\1\0\2\164\1\171\1\167\7\164\1\0\16\164"+
    "\2\0\1\62\3\0\1\13\1\172\1\0\1\61\5\62"+
    "\2\13\1\0\16\62\2\0\3\172\1\0\1\172\1\0"+
    "\1\173\1\174\7\172\1\0\16\172\2\0\3\172\1\0"+
    "\2\172\1\175\1\174\7\172\1\0\16\172\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2816];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\11\0\1\11\1\1\1\11\1\1\1\11\2\1\3\11"+
    "\1\1\2\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\2\11\1\1\1\11"+
    "\1\1\2\11\1\1\1\11\2\1\2\11\4\1\1\11"+
    "\6\1\1\0\11\1\1\11\2\1\1\11\6\1\2\11"+
    "\1\0\5\1\1\0\1\11\5\1\1\11\1\1\1\0"+
    "\4\1\1\0\1\1\1\0\1\1\2\11\1\1\1\11"+
    "\1\0\7\1\1\0\1\1\1\11\1\0\2\1\1\0"+
    "\1\11\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */

// external state of file

public static String login="original";


// tokens
public static final int TOKEN_ADDQ=24;
public static final int TOKEN_ADDA=25;
public static final int TOKEN_ADDQ_H=26;
public static final int TOKEN_ADDA_H=27;
public static final int TOKEN_INLINE_EQ=30;
public static final int TOKEN_MLE=32;
public static final int TOKEN_MLE_IN_Q=33;
public static final int TOKEN_MLE_IN_A=34;
public static final int TOKEN_PART=37;
public static final int TOKEN_SUB_PART=38;
public static final int TOKEN_TITLE=39;

// serializing constants for multiline paterns
public static final int BALANCE_MULT = 1000;
public static final int BALANCE_DEC = 0; // cumulative balance of bracket should never be negative ;-)
public static final int FORMER_BALANCE_MULT = BALANCE_MULT*100;
public static final int FIRST_MULT = FORMER_BALANCE_MULT*10;

// lastToken = token_type + BALANCE_MULT*(balance + dec) +FORMER_BALANCE_MULT*formerBalanceCount 
// where balance is nb of "{" minus nb of "}" for the current line
// and block is the amount of blocks already recovered (\frac{a}{v} requires two for instance)
// and first is 1 if a multiline block started on this line ; 0 else

        protected int bracketCount=0;
        protected int formerBalanceCount=0;
        protected boolean first = false; // boolean flag used for indentation at the begining of a new block

	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public LatexTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *                    occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	@Override
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * ${inheritDoc}
	 */
	@Override
	public String[] getLineCommentStartAndEnd(int languageIndex) {
		return new String[] { "%", null };
	}

        /**
        *          DEALING WITH INDENT
        **/
       @Override
        public boolean getShouldIndentNextLineAfter(Token token) {
            if (!first || token==null){return false;}
            
            switch(token.getType()%BALANCE_MULT){
                 case  TOKEN_ADDQ :
                    return true;
                    
                case  TOKEN_MLE :
                    return true;
                    
                case TOKEN_MLE_IN_A:
                    return true;
                    
                case TOKEN_MLE_IN_Q :
                    return true;

                case Token.RESERVED_WORD :
                    return true;
            }
               

            return false;
        }


        /**
        *          DEALING WITH BRACKETS
        **/

    

        public void initBracketBlock(){
            formerBalanceCount = 0;
            bracketCount = 0;
        }

        public void enterBracketBlock(){
            formerBalanceCount = bracketCount; // the bracketCount must be saved as we may be in a block inside a former block which will need to be closed after
            bracketCount = 0;
        }

        public void leaveBracketBlock(){
            bracketCount = formerBalanceCount;
            formerBalanceCount = 0; 
        }

        public int getLastTokenVal(int tokenType){
            return tokenType + BALANCE_MULT*(bracketCount + BALANCE_DEC) + FORMER_BALANCE_MULT * formerBalanceCount ;
        }

        

        public void addOpenBracket(){
            bracketCount ++;
        }

        public void addCloseBracket(){
            bracketCount -- ;
        }

        public boolean isEndOfBlock(){
            return bracketCount==0;
        }

    public void conditionalReturnToInitial(int state) {
        // check wheter in bracker block is closed and switch state if yes.
        if (isEndOfBlock()) {
            leaveBracketBlock();
            switch(zzLexicalState){
                case  ADDQ:
                    this.addToken(TOKEN_ADDQ);
                    break;
                    
                case ADDA:
                    this.addToken(TOKEN_ADDA);
                    break;
                    
                default:
                    this.addToken(Token.SEPARATOR);
                    break;
            
            }

            yybegin(state);

        } else {
            this.addToken(Token.SEPARATOR);
        }
    }

        
        public void conditionalSwitch(String logins, int stateTrue, int stateFalse){
            int newState =  logins.contains(login) ? stateTrue : stateFalse;
            yybegin(newState);
        }

        /**
        *   Dealing with blocks
        **/
        public void beginMLE(int newState){
            addToken(zzStartRead,zzMarkedPos-2, Token.FUNCTION);
            addToken(zzMarkedPos-1,zzMarkedPos-1, Token.SEPARATOR);
            first=true;
            enterBracketBlock();
            addOpenBracket();
            yybegin(newState);
        }

        public void beginADDQ(int newState){
            addToken(zzStartRead,zzMarkedPos-2, TOKEN_ADDQ);
            addToken(zzMarkedPos-1,zzMarkedPos-1, TOKEN_ADDQ);
            first=true;
            initBracketBlock();
            addOpenBracket();
            yybegin(newState);
        }

	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	@Override
	public Token getTokenList(Segment text, int previousLineData, int startOffset) {

		resetTokenList();
                
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = YYINITIAL;

                // deserialize initialTokenType : 
                first = false;
                int initialTokenType =  previousLineData % BALANCE_MULT ;
                initBracketBlock(); // to be removed ?
                formerBalanceCount =  (previousLineData)/ FORMER_BALANCE_MULT;
                bracketCount = (previousLineData%FORMER_BALANCE_MULT) / BALANCE_MULT - BALANCE_DEC;
                    
                start = text.offset;
	        switch (initialTokenType) {
		
			case TOKEN_MLE:
				state = MLE;
				break;

                         case TOKEN_MLE_IN_Q:
				state = MLE_IN_Q;
				break;

                         case TOKEN_MLE_IN_A:
				state = MLE_IN_A;
				break;

                         case TOKEN_ADDQ:
				state = ADDQ;
				break;

                         case TOKEN_ADDQ_H:
				state = HIDDEN_ADDQ;
				break;

                         case TOKEN_ADDA_H:
				state = HIDDEN_ADDA;
				break;

                         case TOKEN_ADDA:
				state = ADDA;
				break;

			default:
				state = YYINITIAL;
                                 initBracketBlock();
		}
                               

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new TokenImpl();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 * @exception   IOException  if any I/O-Error occurs.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LatexTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LatexTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  

  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { addCloseBracket(); conditionalReturnToInitial(ADDQ);
          }
        case 35: break;
        case 33: 
          { int temp = zzStartRead+4;
                                                     addToken(temp-4,temp+6,Token.FUNCTION); 
                                                     addToken(temp+7,temp+7,Token.SEPARATOR); 
                                                     addToken(temp+8,zzMarkedPos-2,TOKEN_SUB_PART); 
                                                     addToken(zzMarkedPos-1,zzMarkedPos-1,Token.SEPARATOR);
          }
        case 36: break;
        case 19: 
          { addToken( TOKEN_ADDQ);
          }
        case 37: break;
        case 31: 
          { int temp = zzStartRead;
                                                addToken(temp, temp+5, Token.RESERVED_WORD);
                                                addToken(temp+6, temp+6, Token.RESERVED_WORD);
                                                addToken(temp+7, zzMarkedPos-2, Token.RESERVED_WORD);
                                                addToken(zzMarkedPos-1, zzMarkedPos-1, Token.RESERVED_WORD);
                                                first = true;
          }
        case 38: break;
        case 29: 
          { int temp = zzStartRead;
                                                addToken(temp, temp+3, Token.RESERVED_WORD);
                                                addToken(temp+4, temp+4, Token.RESERVED_WORD);
                                                addToken(temp+5, zzMarkedPos-2, Token.RESERVED_WORD);
                                                addToken(zzMarkedPos-1, zzMarkedPos-1, Token.RESERVED_WORD);
          }
        case 39: break;
        case 23: 
          { int temp = zzStartRead; addToken(temp, temp, Token.SEPARATOR); addToken(temp + 1, temp + 1, Token.IDENTIFIER);
          }
        case 40: break;
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 41: break;
        case 14: 
          { addToken( TOKEN_ADDQ_H); addOpenBracket();
          }
        case 42: break;
        case 8: 
          { addCloseBracket(); conditionalReturnToInitial(YYINITIAL);
          }
        case 43: break;
        case 32: 
          { int temp = zzStartRead;
                                                     addToken(temp,temp+6,Token.FUNCTION); 
                                                     addToken(temp+7,temp+7,Token.SEPARATOR); 
                                                     addToken(temp+8,zzMarkedPos-2,TOKEN_PART); 
                                                     addToken(zzMarkedPos-1,zzMarkedPos-1,Token.SEPARATOR);
          }
        case 44: break;
        case 9: 
          { addToken( TOKEN_MLE_IN_Q);
          }
        case 45: break;
        case 12: 
          { addCloseBracket(); conditionalReturnToInitial(ADDA);
          }
        case 46: break;
        case 17: 
          { addToken( TOKEN_ADDA_H); addOpenBracket();
          }
        case 47: break;
        case 20: 
          { addToken( TOKEN_ADDA);
          }
        case 48: break;
        case 15: 
          { addToken( TOKEN_ADDQ_H); addCloseBracket(); conditionalReturnToInitial(HIDDEN_ADDA);
          }
        case 49: break;
        case 2: 
          { addToken(Token.WHITESPACE);
          }
        case 50: break;
        case 11: 
          { addToken( TOKEN_MLE_IN_A);
          }
        case 51: break;
        case 25: 
          { beginMLE(MLE);
          }
        case 52: break;
        case 4: 
          { addToken(Token.SEPARATOR);
          }
        case 53: break;
        case 21: 
          { addToken( bracketCount == 0 ? TOKEN_ADDA : Token.SEPARATOR); addOpenBracket();
          }
        case 54: break;
        case 18: 
          { addToken( TOKEN_ADDA_H); addCloseBracket(); conditionalReturnToInitial(YYINITIAL);
          }
        case 55: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 56: break;
        case 24: 
          { int temp = zzStartRead; addToken(temp, zzMarkedPos-1, TOKEN_INLINE_EQ);
          }
        case 57: break;
        case 22: 
          { addToken(Token.FUNCTION);
          }
        case 58: break;
        case 13: 
          { addToken( TOKEN_ADDQ_H);
          }
        case 59: break;
        case 6: 
          { addToken( TOKEN_MLE);
          }
        case 60: break;
        case 34: 
          { int temp = zzStartRead+7;
                                                     addToken(temp-7,temp+6,Token.FUNCTION); 
                                                     addToken(temp+7,temp+7,Token.SEPARATOR); 
                                                     addToken(temp+8,zzMarkedPos-2,TOKEN_TITLE); 
                                                     addToken(zzMarkedPos-1,zzMarkedPos-1,Token.SEPARATOR);
          }
        case 61: break;
        case 26: 
          { beginMLE(MLE_IN_Q);
          }
        case 62: break;
        case 16: 
          { addToken( TOKEN_ADDA_H);
          }
        case 63: break;
        case 7: 
          { addToken( Token.SEPARATOR); addOpenBracket();
          }
        case 64: break;
        case 28: 
          { beginADDQ(ADDQ);
          }
        case 65: break;
        case 27: 
          { beginMLE(MLE_IN_A);
          }
        case 66: break;
        case 30: 
          { String logins = yytext(); first=true;
                                                       //addToken(zzStartRead,zzStartRead+5,TOKEN_ADDQ_H);
                                                       //addToken(zzStartRead+6,zzMarkedPos-3,TOKEN_ADDQ); 
                                                       //addToken(zzMarkedPos-2,zzMarkedPos-1,TOKEN_ADDQ_H); 
                                                         addToken(TOKEN_ADDQ);
                                                      initBracketBlock(); addOpenBracket();
                                                      logins=logins.substring(6,logins.length()-2);
                                                      conditionalSwitch(logins,ADDQ,HIDDEN_ADDQ);
          }
        case 67: break;
        case 3: 
          { addToken(Token.COMMENT_EOL);
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case HIDDEN_ADDQ: {
              addToken( getLastTokenVal(TOKEN_ADDQ_H)); return firstToken;
            }
            case 126: break;
            case EOL_COMMENT: {
              addToken( Token.NULL); return firstToken;
            }
            case 127: break;
            case MLE_IN_A: {
              addToken( getLastTokenVal(TOKEN_MLE_IN_A)); return firstToken;
            }
            case 128: break;
            case MLE: {
              addToken( getLastTokenVal(TOKEN_MLE)); return firstToken;
            }
            case 129: break;
            case ADDA: {
              addToken( getLastTokenVal(TOKEN_ADDA)); return firstToken;
            }
            case 130: break;
            case MLE_IN_Q: {
              addToken( getLastTokenVal(TOKEN_MLE_IN_Q)); return firstToken;
            }
            case 131: break;
            case ADDQ: {
              addToken( getLastTokenVal(TOKEN_ADDQ)); return firstToken;
            }
            case 132: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 133: break;
            case HIDDEN_ADDA: {
              addToken( getLastTokenVal(TOKEN_ADDA_H)); return firstToken;
            }
            case 134: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
